# Generated by Django 5.0.6 on 2024-06-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(choices=[('QIZIL', 'qizil'), ('OQ', 'oq'), ('QORA', 'QORA')], default='OQ', max_length=9)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(upload_to='carimage/')),
            ],
            options={
                'verbose_name_plural': 'Car',
            },
        ),
    ]
