# Generated by Django 5.0.6 on 2024-07-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yoqtirgan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nami', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Yoqtirgan',
            },
        ),
    ]
