# Generated by Django 5.0.6 on 2024-07-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_yoqtirgan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Yoqtirgan',
        ),
        migrations.AddField(
            model_name='car',
            name='like',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
