# Generated by Django 5.0.6 on 2024-07-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_delete_yoqtirgan_car_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='like',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
